feat: add eslint
BKDN-University/bkdnOJ-reborn-frontend pull request #20
Opened 2022-09-12 08:13 UTC by quangnmwork

What's news : 

- Fix js,jsx trong src
- Add new script (npm run lint)

2022-09-13 09:31 UTC, nvatuan commented
Nhờ @trinhdvt pull về test giúp với, coi có vấn đề gì không.

2022-09-13 09:43 UTC, nvatuan reviewed
Em không push change của build lên nhé

2022-09-13 09:43 UTC, nvatuan commented on .env.copy
>  REACT_APP_BACKEND_PORT=8000
Không change những file .copy e, nó kiểu như template ấy.

2022-09-13 09:43 UTC, nvatuan commented on src/App.js
> +                      <RecentSubmissionSidebar key={2} />,
- Cho a hỏi mục đích của set key này là gì vậy e?
- Với lại sao e không set key cụ thể chút: `sub-filter-sb-1`, `rc-sub-sb-2`? Vì a lo đặt vậy nó trùng key, mà a ko rõ React nó có check phân biệt key giữa các components khác nhau ko

2022-09-13 13:13 UTC, trinhdvt commented
> Nhờ @trinhdvt pull về test giúp với, coi có vấn đề gì không.

Thấy vẫn chạy bth, chưa có lỗi gì. Bro có thể check lại ở [đây](https://bkdn-q0d5fcd3u-trinhdvt.vercel.app/)

2022-09-13 13:14 UTC, trinhdvt approved these changes

2022-09-14 08:53 UTC, nvatuan requested changes

2022-09-14 08:53 UTC, nvatuan commented on src/App.js
> +                    <SubFilterSidebar key={"subFilterSidebar"} />,
```suggestion
                    <SubFilterSidebar key={"SubFilterSidebar"} />,
```
Viết hoa ký tự đầu cho giống mấy cái key còn lại e

2022-09-14 09:40 UTC, merged